sudo: false
language: java
notifications:
  email: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install: wget https://gist.githubusercontent.com/Doridian/01cb63301fe4d022f533bd221e227970/raw/0771d2c50808b295abfbabe266be7368c3273974/settings.xml
  -O settings.bin
script: mvn deploy -DaltDeploymentRepository=deployment-repo-id::default::https://maven.doridian.net/repository/maven-snapshots/
  --settings settings.bin
env:
  global:
  - secure: qZnISUTUBhjU1taEVYwMBZ9k5cFrOhESKhPqmUBGvwny+Y062vet/cIJN0+r7YOOz2bkM3DYHDCsDm+SUuxEfVr/32I4Z61zTBO6USzd9fdgDqAxAxoFPT+6hjnb4D5/TNHE65WbtUGJabLBJXIdJ2UE8fqUJfgAqCj1+RtbrFJnZDpU7dH+3VSmW4Ig9YBGfabsCaBrAAycx8C0CKJA26fyq8L+hD4a9bivE3bwq6+ktwB1tKSHLthEu3lQrK0J6PAHtmxe4zG+IK4KBEkuUFNDUccqOw+FTFogxPQe8wI2ge5/flArzxG3kjnvDhLMzgZpshQrVILdNY8Z8plVckmwWE3A+8S3JF41FLb47lXly5n0VHBmgSQ4XTkTLTNQUgYQIOE/eUtGmLhQw+sUXRHMgmzE+eNcnI3r1xFv4aJ+1R9tz9c/rFolfs5CQIJ7bimF4r8asmo27qxSko0+Q1gjRKhpOQwUzpN0M6oqau3CuQjWc9nH5XOBs2ejuKsoTXY7k5dw8Fxv9EBdoyQTccfo5Cm+2KzOi2XEJXJXMfDfBKT8Mj7vhIFkouipakjPwMoVYVVgBDoriD6dMGNiU8SxmeDwNb6WPACk8/IkystxwN3DWHfYpIU+muec27G8vSQr2oYzbh9tbClPf4F8pP6fz7sznGON2qWXIfBjybY=
  - secure: UELz1TwMjDdjs/teNbgTG2C665+1g4JfPEg2n7E6800dvjMeWNdMyVewjCGFHVnuSPHcndNhcdM5EssM24LNcdP61OINRkgUMqZ2Fpi3ArSiJvMfDTPQXypT40yZiZQi2MmtOJj5tnll/rW0aSM8w4vkzw8yezKbiGLivDI3EjBab3GoKhElyQeiUpHfdKhBSS71sCQXzdk6CgKe5A1hCxvYShAQerXwJtp2pvi+GH4/i85xaDREGG2vfRfFP4ACEd+3FMhXll4sXb2d58pogmXew/LXUtd+P+/W58CBbs0OHHtGEzC7vx89dj1FitEt1DpQ3aMRxE/crz917GZpYXqQybXyJdhzevNZPkMGoGaS2Y14WvOlK610EgU10IOacn6vtzIdlE7MgOXKdQSdSyikkVq4bxCemrY7o1OzRx1wtXEKGCkblKrR6Nf0+Sn/ssSkunS84PaXma2LjznG0tqCoxPKr2gDHNjxKKexW5EitxW/6Z8lY53Y35mbvd2qoLJ9Q7MsJLXR1Fo25Ug3JOONMVCFxFhMXWzlbUHlX5woKAUUSsHGnz7btJJ8FViALYSjvYWJ8kWAtIH3tLmAHlrZWiwe3fGHsmM8XGFVd4CJkJHR/vS7/BJrN/XGSNQFp91GL3vJz01JeRENiNXSh+6HNiUrhAaXYsNUXF9D6ek=
